version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/code"
    schedule:
      interval: "monthly"
    versioning-strategy: increase
    commit-message:
      prefix: "[Dependency Update]"
    groups:
      dependencies:
        patterns:
          - "*"
  - package-ecosystem: "npm"
    directory: "/code/core"
    schedule:
      interval: "monthly"
    versioning-strategy: increase
    commit-message:
      prefix: "[Dependency Update]"
    groups:
      dependencies:
        patterns:
          - "*"
  - package-ecosystem: "npm"
    directory: "/code/adapters/shared"
    schedule:
      interval: "monthly"
    versioning-strategy: increase
    commit-message:
      prefix: "[Dependency Update]"
    groups:
      dependencies:
        patterns:
          - "*"
  - package-ecosystem: "npm"
    directory: "/code/adapters/express"
    schedule:
      interval: "monthly"
    versioning-strategy: increase
    commit-message:
      prefix: "[Dependency Update]"
    groups:
      dependencies:
        patterns:
          - "*"
  - package-ecosystem: "npm"
    directory: "/code/adapters/nestjs"
    schedule:
      interval: "monthly"
    versioning-strategy: increase
    commit-message:
      prefix: "[Dependency Update]"
    groups:
      dependencies:
        patterns:
          - "*"
