version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/code"
    schedule:
      interval: "monthly"
    cooldown:
      default-days: 7
    versioning-strategy: increase
    commit-message:
      prefix: "[Dependency Update]"
    ignore:
      - dependency-name: "typescript"
        update-types:
          - "version-update:semver-major"
    groups:
      typescript:
        patterns:
          - "typescript"
      dependencies:
        patterns:
          - "*"
        exclude-patterns:
          - "typescript"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    cooldown:
      default-days: 7
    commit-message:
      prefix: "[CI Update]"
    groups:
      dependencies:
        patterns:
          - "*"
